
services:
  - type: web
    name: painel-backend
    env: node
    repo: https://github.com/leumas07/painel-quantico
    branch: main
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && node index.js

  - type: web
    name: painel-frontend
    env: node
    repo: https://github.com/leumas07/painel-quantico
    branch: main
    plan: free
    buildCommand: cd web && npm install && npm run build
    startCommand: cd web && npm run preview
